import SpreadsheetTable from "../../components/tables/SpreadsheetTable";

export default function KpiTable() {
  // Dummy spreadsheet data
  const tableData = [
    {
      Tag: "56-FFC618",
      PV: 52.31,
      SP: 50,
      OP: 44.2,
      Mode: "AUTO",
      Status: "Running",
      Error: 2.31,
      Quality: "Good",
      Timestamp: "09:45:01",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 52.45,
      SP: 50,
      OP: 44.6,
      Mode: "AUTO",
      Status: "Running",
      Error: 2.45,
      Quality: "Good",
      Timestamp: "09:45:02",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 52.62,
      SP: 50,
      OP: 45.1,
      Mode: "AUTO",
      Status: "Running",
      Error: 2.62,
      Quality: "Good",
      Timestamp: "09:45:03",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 52.81,
      SP: 50,
      OP: 45.3,
      Mode: "AUTO",
      Status: "Running",
      Error: 2.81,
      Quality: "Good",
      Timestamp: "09:45:04",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 53.02,
      SP: 50,
      OP: 45.7,
      Mode: "AUTO",
      Status: "Running",
      Error: 3.02,
      Quality: "Good",
      Timestamp: "09:45:05",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 52.31,
      SP: 50,
      OP: 44.2,
      Mode: "AUTO",
      Status: "Running",
      Error: 2.31,
      Quality: "Good",
      Timestamp: "09:45:01",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 52.45,
      SP: 50,
      OP: 44.6,
      Mode: "AUTO",
      Status: "Running",
      Error: 2.45,
      Quality: "Good",
      Timestamp: "09:45:02",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 52.62,
      SP: 50,
      OP: 45.1,
      Mode: "AUTO",
      Status: "Running",
      Error: 2.62,
      Quality: "Good",
      Timestamp: "09:45:03",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 52.81,
      SP: 50,
      OP: 45.3,
      Mode: "AUTO",
      Status: "Running",
      Error: 2.81,
      Quality: "Good",
      Timestamp: "09:45:04",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 53.02,
      SP: 50,
      OP: 45.7,
      Mode: "AUTO",
      Status: "Running",
      Error: 3.02,
      Quality: "Good",
      Timestamp: "09:45:05",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 52.31,
      SP: 50,
      OP: 44.2,
      Mode: "AUTO",
      Status: "Running",
      Error: 2.31,
      Quality: "Good",
      Timestamp: "09:45:01",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 52.45,
      SP: 50,
      OP: 44.6,
      Mode: "AUTO",
      Status: "Running",
      Error: 2.45,
      Quality: "Good",
      Timestamp: "09:45:02",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 52.62,
      SP: 50,
      OP: 45.1,
      Mode: "AUTO",
      Status: "Running",
      Error: 2.62,
      Quality: "Good",
      Timestamp: "09:45:03",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 52.81,
      SP: 50,
      OP: 45.3,
      Mode: "AUTO",
      Status: "Running",
      Error: 2.81,
      Quality: "Good",
      Timestamp: "09:45:04",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 53.02,
      SP: 50,
      OP: 45.7,
      Mode: "AUTO",
      Status: "Running",
      Error: 3.02,
      Quality: "Good",
      Timestamp: "09:45:05",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 52.31,
      SP: 50,
      OP: 44.2,
      Mode: "AUTO",
      Status: "Running",
      Error: 2.31,
      Quality: "Good",
      Timestamp: "09:45:01",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 52.45,
      SP: 50,
      OP: 44.6,
      Mode: "AUTO",
      Status: "Running",
      Error: 2.45,
      Quality: "Good",
      Timestamp: "09:45:02",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 52.62,
      SP: 50,
      OP: 45.1,
      Mode: "AUTO",
      Status: "Running",
      Error: 2.62,
      Quality: "Good",
      Timestamp: "09:45:03",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 52.81,
      SP: 50,
      OP: 45.3,
      Mode: "AUTO",
      Status: "Running",
      Error: 2.81,
      Quality: "Good",
      Timestamp: "09:45:04",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
    {
      Tag: "56-FFC618",
      PV: 53.02,
      SP: 50,
      OP: 45.7,
      Mode: "AUTO",
      Status: "Running",
      Error: 3.02,
      Quality: "Good",
      Timestamp: "09:45:05",
      Unit: "%",
      Min: 0,
      Max: 100,
      Alarm: "None",
    },
  ];

  return (
    <div className="flex h-full flex-col">
      {/* Header */}
      <div className="border-b border-[var(--color-border)] px-4 py-3 shrink-0">
        <h3 className="text-sm font-semibold text-[var(--color-text-primary)]">
          View Data for 56-FFC618 Data Preprocessing
        </h3>
      </div>

      {/* Table */}
      <div className="flex-1 overflow-hidden p-4">
        <SpreadsheetTable data={tableData} />
      </div>
    </div>
  );
}
